### ISSUE TITLE
-d does not work in amnesia.drop/amnesia.create

### ISSUE THREAD

**Issue by alecpl** [meh/amnesia#60]
```
# mix amnesia.drop -d Database
** (FunctionClauseError) no function clause matching in Mix.Amnesia.ensure_database_module/1
    lib/mix/mix_amnesia.ex:10: Mix.Amnesia.ensure_database_module(nil)
    lib/mix/amnesia.drop.ex:10: Mix.Tasks.Amnesia.Drop.run/1
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
    (elixir) lib/code.ex:363: Code.require_file/2
```
There's no error if I replace `-d` with `--database`. I'm using amnesia 0.2.5, mix 1.3.3.

**Comment by nazarsh** [comment]
+1
